#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run build:plugin

echo "Running type checking on min supported version...\n"
npx -p typescript@4.8 tsc --incremental --noEmit

echo "Running type checking on latest version...\n"
npx -p typescript@latest tsc --incremental --noEmit
