#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running type checking on min supported version."
npm run typeChecking
echo "Running type checking on latest version."
npx -p typescript@latest tsc --incremental --noEmit
